name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # https://github.com/gautamkrishnar/blog-post-workflow

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: sposigor/blog@v1
        with:
          feed_list: "https://dev.to/feed/sposigor"
